main:
  - name: Knowledge Base
    pageRef: /knowledge-base
    weight: 1
  - name: Blog
    pageRef: /blog
    weight: 2
  - name: Matrix
    url: "https://matrix.to/#/@fovir:matrix.fovir.fyi"
    weight: 3
    params:
      type: link
      icon: chat
  - name: Search
    weight: 7
    params:
      type: search
  - name: Codeberg
    url: "https://codeberg.org/Fovir"
    weight: 8
    params:
      icon: codeberg
  - name: GitHub
    weight: 9
    url: "https://github.com/Fovir-GitHub"
    params:
      icon: github
  - name: RSS
    pageRef: /index.xml
    weight: 10
    params:
      icon: rss
